import Head from 'next/head'
import { useEffect, useState } from 'react'
import AddEmployee from './addEmployee'
import EmployeeList from './employeeList'

export default function Home() {  
  
  const [employees, setEmployees] = useState([])

  const fetchEmployees = async () => {
    const response = await fetch('./api/employees')
    const data = await response.json()
    setEmployees(data)
    console.log('fetched employees data')
  }

  useEffect(()=>{
    fetchEmployees()
  },[])
  
  return (
    <div className='container'>
      <Head>
        <title>Employees - Basic CRUD</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AddEmployee fetchEmployees={fetchEmployees} employees={employees}/>
      <div className='employees-container'>
        <h2>Employee List</h2>
        {
          employees.map(employee => <EmployeeList key={employee.employee_id} employee={employee} fetchEmployees={fetchEmployees}/>)
        }
      </div>

    </div>
  )
}
